crop_box_filter:
  ros__parameters:
    min_x: -3.0
    max_x:  2.0
    min_z: -0.2
    max_z:  2.0
    min_y: -2.0
    max_y:  2.0

    output_frame: "base_link"
    publish_frame: "map"
    leaf_size: 0.03
    use_latest_tf: true
    tf_timeout_sec: 0.2
    publish_marker: true
    marker_alpha: 0.15