rtabmap:
  ros__parameters:
    # Frames / TF
    frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    publish_tf: true
    wait_for_transform: 0.2

    # Sync/queues
    approx_sync: true
    approx_sync_max_interval: 0.02
    queue_size: 30

    # Mapping resolution
    Grid/CellSize: "0.02"
    Grid/MinDepth: "0.2"

    # Behavior
    delete_db_on_start: true
    verbose: false
